# Generated by Django 4.2.2 on 2023-06-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emploie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=128)),
                ('entreprise', models.CharField(max_length=128)),
                ('departement', models.IntegerField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
