# Generated by Django 4.2.2 on 2023-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploie',
            name='description',
            field=models.TextField(default='not things'),
            preserve_default=False,
        ),
    ]
