# Generated by Django 4.2.2 on 2023-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_emploie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploie',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
