# Generated by Django 4.2.2 on 2023-06-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_description_emploie_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploie',
            name='ville',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
