# Generated by Django 4.2.2 on 2023-06-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_emploie_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploie',
            name='slug',
            field=models.SlugField(default='not', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emploie',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo'),
        ),
    ]
